import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const html = readFileSync("dist/client/index.html", "utf-8");

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/spa-html.ts",
  `// Auto-generated by scripts/generate-spa-html.ts -- do not edit\nexport const spaHtml = ${JSON.stringify(html)};\n`,
);
