import { readFileSync, writeFileSync, mkdirSync, unlinkSync } from "node:fs";

const html = readFileSync("dist/client/index.html", "utf-8");

mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/spa-html.ts",
  `// Auto-generated by scripts/generate-spa-html.ts -- do not edit\nexport const spaHtml = ${JSON.stringify(html)};\n`,
);

// Remove index.html from the assets directory so Cloudflare's asset binding
// doesn't serve it at "/". Without this, the SPA shell would be served
// unauthenticated at the root, bypassing the Worker's auth-gated dashboard route.
unlinkSync("dist/client/index.html");
